#!/bin/bash
echo "=== Audio-to-Mermaid: BlackHole audio setup ==="
echo ""
echo "Step 1: Install BlackHole"
echo "  brew install blackhole-2ch"
echo ""
echo "Step 2: REBOOT your Mac after installing BlackHole (kernel extension)"
echo ""
echo "Step 3: Create Multi-Output Device"
echo "  1. Open 'Audio MIDI Setup' (Spotlight: type 'Audio MIDI Setup')"
echo "  2. Click '+' button at bottom-left -> 'Create Multi-Output Device'"
echo "  3. Check BOTH your speakers/headphones AND 'BlackHole 2ch'"
echo "  4. Drag your speakers to the TOP of the list (master clock)"
echo ""
echo "Step 4: Set system output to the Multi-Output Device"
echo "  System Settings -> Sound -> Output -> select the Multi-Output Device"
echo "  (Or: Option-click the volume icon in the menu bar)"
echo ""
echo "Step 5: Run the app"
echo "  ./AudioToMermaid.command   # or: source .venv/bin/activate && python -m src"
echo ""
echo "See README.md for the rest (venv install, .env, viewer controls)."
