#!/bin/bash
echo "=== Audio-to-Mermaid: Setup Guide ==="
echo ""
echo "Step 1: Install BlackHole"
echo "  brew install blackhole-2ch"
echo "  (Requires sudo - run in your terminal, not through Claude)"
echo ""
echo "Step 2: REBOOT your Mac after installing BlackHole"
echo ""
echo "Step 3: Create Multi-Output Device"
echo "  1. Open 'Audio MIDI Setup' (Spotlight: Cmd+Space, type 'Audio MIDI Setup')"
echo "  2. Click '+' button at bottom-left -> 'Create Multi-Output Device'"
echo "  3. Check BOTH your speakers/headphones AND 'BlackHole 2ch'"
echo "  4. Make sure your speakers are listed FIRST (drag to reorder if needed)"
echo ""
echo "Step 4: Set system output"
echo "  System Settings -> Sound -> Output -> Select the Multi-Output Device"
echo "  (You can also Option-click the volume icon in menu bar)"
echo ""
echo "Step 5: Launch Brave with remote debugging"
echo "  /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --remote-debugging-port=9222"
echo ""
echo "Step 6: Open mermaid.ai in Brave and navigate to a diagram"
echo ""
echo "Step 7: Run the app"
echo "  source .venv/bin/activate"
echo "  python -m src"
echo ""
echo "Hotkeys:"
echo "  Cmd+Shift+M - Toggle diagram generation ON/OFF"
echo "  Cmd+Shift+R - Force regenerate diagram"
echo "  Ctrl+C      - Quit (saves transcript + diagram)"
